/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockAggregator } from "./MockAggregator";
export * as factories from "./factories";
export { MockAggregator__factory } from "./factories/MockAggregator__factory";
